name: Benchmark test

on:
  pull_request:
    types: [opened,edited,sychnronized,labeled]

jobs:
  run-benchmark:
    needs: [check-comments]
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'benchmark')
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - name: Run benchmark
      run: |
        python3 gen_random_result.py | tee ${GITHUB_WORKSPACE}/output.json
    - name: Download previous benchmark data
      uses: actions/cache@v4
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - name: Store new result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: customSmallerIsBetter
        output-file-path: output.json
        external-data-json-path: ./cache/benchmark-data.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        summary-always: true
        comment-always: true
        comment-on-alert: true
